### PR TITLE
Build as a shared library

### PR DESCRIPTION
**Pull request by martinRenou**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by martinRenou** [comment]
Also adding myself as a maintainer, but I can revert this specific change if someone is against it.

**Comment by wolfv** [comment]
I think the previous package should be moved to broken.

**Comment by martinRenou** [comment]
@dschreij Sorry I messed up with yesterday's release. It should be fine now.

**Review by dschreij — APPROVED** [review]
Looks good, and it builds. So let's merge!
Thanks here too! :)

**Comment by martinRenou** [comment]
Thanks!

**Pull request merged**
